# Generated by Django 4.2.7 on 2023-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='nutrition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
